name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 
        uses: actions/setup-java@v1.8
        with:
          java-version: 1.8
      - name: checkout
        uses: actions/checkout@v2
      - name: Build Application
        run: |
          cd Application
          ../gradlew build --stacktrace
  
